version: "3.7"

services:
  main-api:
    build:
      context: .
      dockerfile: AgileX.Api/Dockerfile
    restart: always
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
