namespace AgileX.Domain.ObjectValues;

public enum Permission
{
    LIST_MEMBER_PERMISSIONS,
    GRANT_PERMISSION,
    DELETE_PROJECT,
    UPDATE_PROJECT,
    UPDATE_PROJECT_DEADLINE,
    ADD_MEMBER,
    CREATE_SPRINT,
    UPDATE_SPRINT,
    DELETE_SPRINT,
    CREATE_TICKET,
    CHANGE_TICKET_SPRINT,
    CHANGE_TICKET_DEADLINE,
    DELETE_TICKET,
    CHANGE_SPRINT_DATES,
    ADD_DEPENDENCY,
    DELETE_DEPENDENCY
}
