namespace AgileX.Domain.ObjectValues;

public enum Permission
{
    LIST_MEMBER_PERMISSIONS,
    GRANT_PERMISSION,
    DELETE_PROJECT,
    UPDATE_PROJECT,
    UPDATE_PROJECT_DEADLINE,
    ADD_MEMBER,
    CREATE_SPRINT,
    UPDATE_SPRINT,
    DELETE_SPRINT
}
